'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin_ACADashboard

    '''<summary>
    '''LiteralTopMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralTopMenu As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralTab As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''divTopHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTopHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCompanyList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCompanyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCompany As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCompanyName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAlert As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAlertTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlertMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkEdit As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstReports As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''divACACounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divACACounts As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblALETrend1MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend1MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend2MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend2MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend3MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend3MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend4MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend4MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend5MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend5MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend6MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend6MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend7MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend7MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend8MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend8MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend9MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend9MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend10MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend10MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend11MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend11MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblALETrend12MonthAve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblALETrend12MonthAve As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEdit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlMeasurementMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMeasurementMethod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIntialPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIntialPeriod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlMeasurementPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMeasurementPeriod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlStabilityPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStabilityPeriod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPeriodBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodBegin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAdminPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAdminPeriod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPeriodEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFirstPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstPayroll As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLastIRSReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastIRSReport As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMostRecentPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMostRecentPayroll As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNextIRSReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNextIRSReport As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtALECountBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtALECountBegin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLastACACount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastACACount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtALECountEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtALECountEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Searchtxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Searchtxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''searchbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchbtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblHightlight1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHightlight1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''a_grdEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_grdEmployee As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lnkDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDummy As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''PayTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PayTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PayType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''PayLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PayLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PayInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PayInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ContributionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContributionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContributionInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContributionInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalculateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalculateButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ResetButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResetButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''resultsdiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resultsdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ResultLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RateofPayIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RateofPayIncome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeCont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeCont As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RateofPayPer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RateofPayPer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RateofPayPertxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RateofPayPertxt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RateofPayMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RateofPayMin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AffortablePerc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AffortablePerc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FPLIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FPLIncome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeContFPL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeContFPL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FPLPer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FPLPer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FPLPertxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FPLPertxt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FPLMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FPLMin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AffortablePercFPL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AffortablePercFPL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divReviewDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReviewDocuments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkActiveOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActiveOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnDocAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDocAdd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''grdDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDocument As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LinkButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAdd As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFileUpload As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''fuLoad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuLoad1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''divWebLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWebLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShortDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShortDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileUpload As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCancelNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNew As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnSaveNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNew As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''divReviewACARules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReviewACARules As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMeasurementMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMeasurementMethod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIntialPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIntialPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMeasurementPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMeasurementPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStabilityPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStabilityPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPeriodBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodBegin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdmistrativePeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdmistrativePeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPeriodEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodEnd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirstPayrollAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstPayrollAvailable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastIRSReportDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastIRSReportDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMostRecentPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMostRecentPayroll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextIRSReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextIRSReport As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastALECountBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastALECountBegin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastALECount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastALECount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastALECountEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastALECountEnd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEditRules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditRules As Global.System.Web.UI.WebControls.ImageButton
End Class
