'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EE_AdditionalInfo

    '''<summary>
    '''LiteralTopMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralTopMenu As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralTab As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''imgNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNext As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProcessing As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''divMainArticalTitleandText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMainArticalTitleandText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMainArticleTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainArticleTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DivMainArticleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMainArticleText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMainArticleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainArticleText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LeftDocument1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeftDocument1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLeftDocument1Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeftDocument1Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlLeftDocument1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLeftDocument1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LeftDocument2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeftDocument2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLeftDocument2Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeftDocument2Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlLeftDocument2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLeftDocument2 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LeftDocument3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeftDocument3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLeftDocument3Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeftDocument3Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlLeftDocument3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLeftDocument3 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''MiddleColumnDoc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiddleColumnDoc1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRightDocument1Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRightDocument1Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRightDocument1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRightDocument1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''MiddleColumnDoc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiddleColumnDoc2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRightDocument2Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRightDocument2Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRightDocument2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRightDocument2 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''MiddleColumnDoc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiddleColumnDoc3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRightDocument3Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRightDocument3Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRightDocument3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRightDocument3 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''RightColumnDoc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RightColumnDoc1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSideMenu1Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideMenu1Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSideMenu1text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideMenu1text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RightColumnDoc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RightColumnDoc2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSideMenu2Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideMenu2Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSideMenu2text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideMenu2text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RightColumnDoc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RightColumnDoc3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSideMenu3Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideMenu3Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSideMenu3text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideMenu3text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAccept As Global.System.Web.UI.WebControls.ImageButton
End Class
