'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EE_W4_CA

    '''<summary>
    '''LiteralTopMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralTopMenu As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralTab As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DivError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LabelError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DivSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSuccess As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LabelSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSuccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNext As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProcessing As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TextAllowance1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAllowance1A As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAllowance1B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAllowance1B As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAllowance1C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAllowance1C As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAllowance1D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAllowance1D As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAllowance1E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAllowance1E As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAllowance1F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAllowance1F As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextDeduction11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextDeduction11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextEstimatedTax15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEstimatedTax15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFullName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelSSNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSSNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelFullAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFullAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckboxSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckboxSingle As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckboxMarried control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckboxMarried As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckboxHOH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckboxHOH As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelCityStateZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCityStateZipCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextAllowancesWorksheetA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAllowancesWorksheetA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAllowancesWorksheetB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAllowancesWorksheetB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextTotalExemptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextTotalExemptions As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextAdditionalWithholding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAdditionalWithholding As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckboxExempt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckboxExempt1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckboxExempt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckboxExempt2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TextSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextSignature As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SignatureDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignatureDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCompanyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCompanyAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCompanyCityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCompanyCityStateZip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelEmployerPTANo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEmployerPTANo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.ImageButton
End Class
