'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EE_W4_IA

    '''<summary>
    '''LiteralTopMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralTopMenu As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralTab As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''divError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSuccess As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNext As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProcessing As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtAllowanceA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowanceA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAllowanceB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowanceB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAllowanceC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowanceC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdoSingle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoSingle As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdoMarried control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoMarried As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblEmployeeFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeFullName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSNumber1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHomeAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHomeAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployeeCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployeeState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEEZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEEZip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExempt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtExemptYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExemptYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkMilitarySpouseRelief control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMilitarySpouseRelief As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtMilitaryDomicileState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMilitaryDomicileState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAllowance1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowance1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAllowance2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowance2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAllowance3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowance3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAllowance4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowance4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAllowance5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowance5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalExemptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalExemptions As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAdditionalWithholding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdditionalWithholding As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SignatureDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignatureDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEmployerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerFEIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerFEIN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerCombinedAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerCombinedAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerZip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerFEIN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerFEIN1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerName1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerCombinedAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerCombinedAddress1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerCity1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerCity1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerState1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerState1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerZip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerZip1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployerPhoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployerPhoneNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNameDiff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameDiff As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddressDiff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressDiff As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCityDiff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCityDiff As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStateDIFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStateDIFF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtZipDIFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipDIFF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkYes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpLastName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpFirstName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpMiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpMiddleName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpZip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.ImageButton
End Class
